pydev debugger: process 10803 is connecting

2016-07-20 16:38:07,955 werkzeug     INFO      * Running on http://127.0.0.1:3434/ (Press CTRL+C to quit)
2016-07-20 16:38:07,956 werkzeug     INFO      * Restarting with stat
pydev debugger: process 10816 is connecting

2016-07-20 16:38:08,927 werkzeug     WARNING   * Debugger is active!
2016-07-20 16:38:08,936 werkzeug     INFO      * Debugger pin code: 245-963-413
2016-07-20 18:25:19,266 werkzeug     INFO     127.0.0.1 - - [20/Jul/2016 18:25:19] "OPTIONS /user HTTP/1.1" 200 -
2016-07-20 18:25:25,010 werkzeug     INFO     127.0.0.1 - - [20/Jul/2016 18:25:25] "GET /user HTTP/1.1" 200 -
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/rahul/healthify/backend/venv/local/lib/python2.7/site-packages/werkzeug/serving.py", line 659, in inner
    srv.serve_forever()
  File "/home/rahul/healthify/backend/venv/local/lib/python2.7/site-packages/werkzeug/serving.py", line 499, in serve_forever
    HTTPServer.serve_forever(self)
  File "/usr/lib/python2.7/SocketServer.py", line 238, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python2.7/SocketServer.py", line 297, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/home/rahul/healthify/backend/venv/local/lib/python2.7/site-packages/werkzeug/serving.py", line 216, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/rahul/healthify/backend/venv/local/lib/python2.7/site-packages/werkzeug/serving.py", line 251, in handle_one_request
    return self.run_wsgi()
  File "/home/rahul/healthify/backend/venv/local/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/rahul/healthify/backend/venv/local/lib/python2.7/site-packages/werkzeug/serving.py", line 184, in execute
    write(data)
  File "/home/rahul/healthify/backend/venv/local/lib/python2.7/site-packages/werkzeug/serving.py", line 152, in write
    self.send_header(key, value)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 401, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe

